APP='''.mailapp{position:absolute;left:55px;top:245px;width:970px;height:900px;background:#f4f6f8;color:#172a3b;border-radius:24px;overflow:hidden;box-shadow:0 30px 75px #0009}.apptop{height:78px;background:#fff;border-bottom:1px solid #d5dde5;display:flex;align-items:center;padding:0 28px;gap:26px}.brand{font:800 27px "JetBrains Mono";color:#173d53}.apptop span{font-size:22px;color:#647687}.status{margin-left:auto;background:#dff2ea;color:#26725e;border-radius:20px;padding:8px 15px;font-size:18px}.side{position:absolute;left:0;top:78px;bottom:0;width:205px;background:#e8edf2;padding:28px 20px}.side div{font-size:21px;padding:14px 12px;border-radius:9px;margin-bottom:8px}.side .active{background:#173e55;color:#fff}.work{position:absolute;left:205px;right:0;top:78px;bottom:0;padding:30px}.hint{position:absolute;right:20px;bottom:14px;color:#405565;font-size:17px}.row{position:relative;background:#fff;border:1px solid #d7dfe7;border-radius:12px;padding:18px 20px;margin-bottom:12px}.row b{font-size:24px}.row small{display:block;margin-top:7px;font-size:18px;color:#718291}.row strong{position:absolute;right:20px;top:24px;font:700 22px "JetBrains Mono";color:#267991}.focus{border:4px solid #36a4c4;box-shadow:0 0 0 5px #36a4c422}.chip{display:inline-block;padding:8px 13px;border-radius:18px;background:#e3ebf0;color:#40596a;font-size:19px;margin:5px}.chip.on{background:#1f7892;color:white}.btn{background:#173e55;color:#fff;border-radius:9px;text-align:center;padding:16px;font-size:23px;font-weight:800}.toggle{width:62px;height:32px;border-radius:20px;background:#acb9c4;position:relative}.toggle:after{content:"";position:absolute;width:24px;height:24px;border-radius:50%;background:#fff;left:4px;top:4px}.toggle.on{background:#2b8ba5}.toggle.on:after{left:34px}.sample{position:absolute;right:18px;bottom:14px;color:#405565;font-size:17px}'''
def shell(active,inner):
    nav=''.join(f'<div class="{"active" if x==active else ""}">{x}</div>' for x in ['성과','고객군','캠페인','권한'])
    return f'<div class="mailapp"><div class="apptop"><b class="brand">MAIL WORKSPACE</b><span>AI assistant</span><i class="status">연결됨</i></div><div class="side">{nav}</div><div class="work">{inner}</div><div class="sample">화면 예시 · 실제 고객 정보 아님</div></div>'
COMPACT='.mailapp{left:64px;top:300px;width:952px;height:520px}.mailapp .work{overflow:hidden}.mailapp .side{padding-top:12px}.mailapp .side div{padding:8px 12px}.mailapp .sample{display:none}'

hook(3.78,6.26,'클로드가 이제','이메일 마케팅까지 직접?')
hire_badge('s02-badge',6.26,8.80,'Email Marketer','OMNI')

add('s03-connect',8.80,13.88,shell('성과','''<div class="connect"><div class="service">Omnisend</div><svg viewBox="0 0 240 80"><path d="M10 40H230"/><circle cx="10" cy="40" r="9"/></svg><div class="service ai">ChatGPT<br><small>또는 Claude</small></div></div><div class="access">계정 데이터 읽기 <b>허용</b></div>'''),APP+COMPACT+'''.connect{display:flex;align-items:center;justify-content:center;gap:18px;margin-top:120px}.service{width:220px;padding:28px 10px;text-align:center;border:2px solid #2b819b;border-radius:14px;font-size:30px;font-weight:900;background:white}.service small{font-size:19px;color:#607889}.connect svg{width:180px;height:80px}.connect path{stroke:#2b819b;stroke-width:5;fill:none;stroke-dasharray:220;stroke-dashoffset:220}.connect circle{fill:#64d2ff}.access{margin:75px auto 0;width:480px;background:white;border:1px solid #d5dee5;border-radius:12px;padding:19px 24px;font-size:22px}.access b{float:right;color:#28798f}''',"tl.fromTo('.mailapp',{opacity:0,y:50},{opacity:1,y:0,duration:.3},0);tl.to('.connect path',{strokeDashoffset:0,duration:.7,ease:'none'},@link);tl.to('.connect circle',{x:220,duration:.7,ease:'none'},@link);tl.fromTo('.access',{opacity:0,y:16},{opacity:1,y:0,duration:.25},@grant);",'card',{'link':(9.36,'ui-tick',-10),'grant':(10.62,'soft-pop',-10)})

add('s04-dashboard',13.88,18.30,shell('성과','''<h2>지난달 캠페인 성과</h2><div class="row r1"><b>봄 클래스 오픈</b><small>4월 3일 · 구독자 전체</small><strong>₩4.8M</strong></div><div class="row r2"><b>주말 리마인드</b><small>4월 12일 · 관심 고객</small><strong>₩3.4M</strong></div><div class="row r3"><b>신규 구독자 안내</b><small>4월 20일 · 신규 고객</small><strong>₩2.1M</strong></div><div class="drawer"><small>선택한 캠페인</small><b>봄 클래스 오픈</b><p>열람률 · 클릭률 · 매출 기여</p></div>'''),APP+COMPACT+'''.work h2{font-size:31px;margin:3px 0 24px}.drawer{position:absolute;left:90px;right:30px;bottom:35px;background:#173e55;color:white;border-radius:14px;padding:23px 28px}.drawer small{font:18px "JetBrains Mono";color:#94c8d8}.drawer b{display:block;font-size:31px;margin:10px 0}.drawer p{font-size:20px;margin:0;color:#c4dae3}''',"tl.fromTo('.row',{opacity:0,x:28},{opacity:1,x:0,stagger:.12,duration:.2},0);tl.set('.drawer',{opacity:0,y:55},0);tl.to('.r1',{className:'row r1 focus',duration:.01},@select);tl.set('.r2,.r3',{autoAlpha:0},@select);tl.to('.drawer',{opacity:1,y:0,duration:.3,ease:'back.out(1.4)'},@select);",'card',{'select':(15.15,'ui-panel-appear',-10)})

add('s05-ask',18.30,20.74,shell('성과','''<div class="ask"><div class="me">지난달 성과를 말로 정리해줘</div><div class="typing"><i></i><i></i><i></i></div></div>'''),APP+'''.ask{padding:90px 30px}.me{margin-left:140px;background:#267d96;color:white;padding:23px 26px;border-radius:22px 22px 5px 22px;font-size:27px}.typing{margin-top:35px;width:130px;background:white;padding:20px;border-radius:20px}.typing i{display:inline-block;width:12px;height:12px;border-radius:50%;background:#6e8798;margin:0 5px}''',"tl.fromTo('.me',{opacity:0,y:20},{opacity:1,y:0,duration:.25},0);tl.fromTo('.typing',{opacity:0},{opacity:1,duration:.2},@ask);tl.to('.typing i',{y:-8,stagger:.1,duration:.18,repeat:3,yoyo:true},@ask);",'card',{'ask':(19.10,'ui-tick',-11)})

add('s06-performance',20.74,25.92,shell('성과','''<h2>매출을 만든 이메일</h2><div class="row winner"><b>봄 클래스 오픈</b><small>지난달 매출 기여 1위</small><strong>₩4.8M</strong></div><div class="insight"><small>공통점 분석</small><div><b>01</b> 제목에 구체적인 혜택</div><div><b>02</b> 한 고객군에 집중</div><div><b>03</b> CTA를 한 번만 제시</div></div>'''),APP+'''.work h2{font-size:31px;margin:3px 0 24px}.winner{border:4px solid #36a4c4}.insight{margin-top:25px;background:#fff;border-radius:14px;padding:23px}.insight small{font:18px "JetBrains Mono";color:#38778c}.insight div{font-size:23px;padding:15px 10px;border-bottom:1px solid #dae2e8}.insight b{color:#25809a;margin-right:20px;font-family:"JetBrains Mono"}''',"tl.fromTo('.winner',{opacity:0,scale:.94},{opacity:1,scale:1,duration:.3},0);tl.fromTo('.insight div',{opacity:0,x:-25},{opacity:1,x:0,stagger:.25,duration:.22},@analyze);",'hide',{'analyze':(23.20,'ui-tick',-10)})

presenter('s07-answer',25.92,28.74)

add('s08-audience-draft',28.74,33.96,shell('고객군','''<div class="builder"><small>AUDIENCE</small><h2>다음 발송 고객군</h2><span class="chip">최근 열람</span><span class="chip">구매 없음</span><span class="chip">30일 이내</span><div class="count">선택 고객 <b>1,284명</b></div></div><div class="compose"><small>EMAIL DRAFT</small><label>제목<input value="다시 만나 반가워요"></label><label>본문<textarea>지난 관심 상품을 바탕으로 새 소식을 준비했습니다.</textarea></label><div class="btn">초안 저장</div></div>'''),APP+'''.work{display:grid;grid-template-columns:1fr 1.15fr;gap:22px}.builder,.compose{background:#fff;border:1px solid #d6dfe6;border-radius:14px;padding:24px}.builder small,.compose small{font:17px "JetBrains Mono";color:#3e7184}.builder h2{font-size:28px}.count{margin-top:38px;border-top:1px solid #d8e0e7;padding-top:22px;font-size:21px}.count b{float:right;color:#267b92}.compose label{display:block;font-size:18px;color:#5e7282;margin:18px 0}.compose input,.compose textarea{display:block;width:100%;margin-top:7px;border:1px solid #c9d5de;border-radius:8px;padding:13px;font:21px Pretendard;color:#172c3c;background:#f7f9fa}.compose textarea{height:130px;resize:none}''',"tl.set('.compose',{opacity:.15},0);tl.to('.chip',{className:'chip on',stagger:.2,duration:.01},@segment);tl.fromTo('.count b',{opacity:0,scale:1.4},{opacity:1,scale:1,duration:.25},@segment+.45);tl.to('.compose',{opacity:1,duration:.25},@draft);tl.fromTo('.compose input,.compose textarea,.compose .btn',{opacity:0,y:12},{opacity:1,y:0,stagger:.15,duration:.2},@draft);",'hide',{'segment':(29.20,'ui-tick',-10),'draft':(30.84,'ui-panel-appear',-10)})

add('s09-permissions',33.96,43.02,shell('권한','''<h2>AI 권한 설정</h2><div class="prow"><span><b>성과 데이터</b><small>캠페인 결과 보기</small></span><i class="toggle on"></i></div><div class="prow write"><span><b>고객군 만들기</b><small>새 고객군 저장</small></span><i class="toggle"></i></div><div class="prow send"><span><b>캠페인 발송</b><small>실제 이메일 전송</small></span><i class="toggle"></i></div><div class="policy">읽기는 기본 · 쓰기는 필요할 때만</div>'''),APP+COMPACT+'''.work h2{font-size:27px;margin:2px 0 10px}.prow{display:flex;justify-content:space-between;align-items:center;background:#fff;border:1px solid #d5dfe6;border-radius:13px;padding:11px 20px;margin-bottom:7px}.prow b{font-size:25px}.prow small{display:block;color:#405565;font-size:19px;margin-top:6px}.policy{margin-top:7px;background:#fff;color:#07101c;padding:8px;border-radius:10px;text-align:center;font-size:18px;font-weight:900}''',"tl.fromTo('.prow',{opacity:0,x:-25},{opacity:1,x:0,stagger:.14,duration:.22},0);tl.to('.write .toggle',{className:'toggle on',duration:.01},@write);tl.fromTo('.policy',{opacity:0,y:15},{opacity:1,y:0,duration:.22},@write);tl.to('.send',{opacity:.45,duration:.25},@separate);",'card',{'write':(40.68,'ui-tick',-10),'separate':(41.86,'soft-pop',-11)})

add('s10-presend',43.02,47.74,shell('캠페인','''<div class="review"><small>PRE-SEND REVIEW</small><h2>봄 클래스 리마인드</h2><div><b>대상</b><span>관심 고객 1,284명</span><i>✓</i></div><div><b>링크</b><span>class.example/apply</span><i>✓</i></div><div class="discount"><b>할인 조건</b><span>20% · 오늘 자정까지</span><i>!</i></div><button>검토 후 발송</button></div>'''),APP+COMPACT+'''.review{background:#fff;border-radius:14px;padding:12px 20px}.review small{font:15px "JetBrains Mono";color:#38778c}.review h2{font-size:27px;margin:7px 0}.review>div{display:grid;grid-template-columns:125px 1fr 38px;align-items:center;border-top:1px solid #d7e0e7;padding:8px 4px;font-size:19px}.review i{font-style:normal;width:30px;height:30px;border-radius:50%;background:#dff0e9;color:#26715f;text-align:center;line-height:30px}.review .discount{background:#fff4e8}.review .discount i{background:#f26d62;color:white}.review button{width:100%;padding:9px;background:#173e55;color:white;border:0;border-radius:8px;font-size:20px;font-weight:800;margin-top:7px}''',"tl.fromTo('.review>div',{opacity:0,x:25},{opacity:1,x:0,stagger:.2,duration:.22},0);tl.fromTo('.discount i',{scale:1.8},{scale:1,duration:.22,ease:'back.out(2)'},@discount);tl.to('.discount',{boxShadow:'0 0 0 4px #f26d6255',duration:.25},@discount);",'card',{'discount':(45.12,'soft-pop',-9)})

presenter('s11-ebook',47.74,52.88)
comment(52.88,56.12,'전자책')
CAM_SRC.append((49.10,'full',1.12,.24))
CAM_SRC.extend([(35.40,'full',1.10,.24),(38.70,'card',1.0,.24)])
