import React from 'react';
import {AbsoluteFill,OffthreadVideo,Sequence,staticFile,useVideoConfig} from 'remotion';
import {CaptionChunk,ProfileCTA,Tokens} from './components/Common';
import {OrenSerifChapterTitle,OrenUpperUiOverlay,OrenReferenceBurst,OrenEvidenceFullscreen} from './components/Oren';
import {JackBigKeyword,JackStoryMontage,JackEvidenceOverlay} from './components/Jack';
export type Scene={id:string;start:number;end:number;scene_type:string;component:string;dialogue:string;display_text?:string;asset_path?:string}; export type Caption={start:number;end:number;text:string;highlight?:string};
export type Props={style:string;scenes:Scene[];captions:Caption[];fps:number;renderDuration?:number;tokens:Tokens};
const Visual:React.FC<{s:Scene;scale:number;tokens:Tokens}>=({s,scale,tokens})=>{const src=s.asset_path?staticFile(s.asset_path):undefined; const t=s.display_text||s.dialogue; const a={src,scale,tokens}; switch(s.component){case'OrenSerifChapterTitle':return <OrenSerifChapterTitle text={t} scale={scale} tokens={tokens}/>;case'OrenUpperUiOverlay':return <OrenUpperUiOverlay {...a}/>;case'OrenReferenceBurst':return <OrenReferenceBurst {...a}/>;case'OrenEvidenceFullscreen':return <OrenEvidenceFullscreen {...a}/>;case'JackBigKeyword':return <JackBigKeyword text={t} scale={scale} tokens={tokens}/>;case'JackStoryMontage':return <JackStoryMontage {...a}/>;case'JackEvidenceOverlay':return <JackEvidenceOverlay {...a}/>;case'ProfileCTA':return <ProfileCTA text={t} scale={scale} tokens={tokens}/>;default:return null}}
export const AutoEditor:React.FC<Props>=({scenes,captions,fps,tokens})=>{const {width}=useVideoConfig();const scale=width/1080;return <AbsoluteFill style={{backgroundColor:'#000'}}><OffthreadVideo src={staticFile('raw.mp4')} muted style={{width:'100%',height:'100%',objectFit:'cover'}}/>{scenes.map(s=>{const from=Math.round(s.start*fps),dur=Math.max(1,Math.round((s.end-s.start)*fps));return <Sequence key={s.id} from={from} durationInFrames={dur}><Visual s={s} scale={scale} tokens={tokens}/></Sequence>})}{(captions||[]).map((c,i)=>{const from=Math.round(c.start*fps),dur=Math.max(1,Math.round((c.end-c.start)*fps));return <Sequence key={`c${i}`} from={from} durationInFrames={dur}><CaptionChunk text={c.text} highlight={c.highlight} scale={scale} tokens={tokens}/></Sequence>})}</AbsoluteFill>};
